#!/bin/bash

set -e

### Install geckodriver

TARGET_ARCH="$(dpkg --print-architecture)"
VERSION="0.36.0"
GECKODRIVER="usr/local/Library/Applications/QRLJacker/geckodriver/"

if [ -e "$GECKODRIVER/geckodriver-$VERSION-$TARGET_ARCH" ];
	ln -s $GECKODRIVER/geckodriver-$VERSION-$TARGET_ARCH /usr/local/bin/geckodriver || echo "Failed to create symlink"
	ln -s $GECKODRIVER/geckodriver-$VERSION-$TARGET_ARCH /usr/local/bin/geckodriver || echo "Failed to create symlink"
	ln -s $GECKODRIVER/geckodriver-$VERSION-$TARGET_ARCH /usr/bin/geckodriver || echo "Failed to create symlink"
else
	echo "Error: $GECKODRIVER/geckodriver-$VERSION-$TARGET_ARCH is MiSSING!" > /tmp/qrljacking-failed.txt
fi

### Give permissing to qrljacker

chmod +x /usr/bin/qrljacker
